common:
    lid_topic:  "/wanda/lidar_points"
    imu_topic:  "/wanda/imu/data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
    
preprocess:
    lidar_type: 3     # 1-Livox serials LiDAR, 2-Velodyne LiDAR, 3-ouster LiDAR, 
    scan_line: 128
    timestamp_unit: 3   # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 3.0

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 180
    det_range: 100.0
    extrinsic_est_en: false # true: enable the online estimation of IMU-LiDAR extrinsic
    #extrinsic_T: [ 0.0, 0.0, 0.0 ]
    #extrinsic_R: [1, 0, 0,
                  #0, 1, 0,
                  #0, 0, 1]
    #extrinsic_T: [ 0.026369, -0.380790,  0.424666]
    #extrinsic_R: [ 0.971149,  0.238461,  0.002400,
                  #-0.238444,  0.970824,  0.025414,
                   #0.003731, -0.025253,  0.999674] # Jackal
    #extrinsic_T: [ 0.03134830, -0.00852594, -0.1005490]
    #extrinsic_R: [ 0.99970800,  0.00460475, -0.0237382,
                  #-0.00385304,  0.99949300,  0.0316158,
                   #0.02387170, -0.03151510,  0.9992180] # CODa
    extrinsic_T: [-0.034803, 0.010012, 0.424886]
    extrinsic_R: [-0.999956, -0.009424, -0.000055,
                   0.009421, -0.999790,  0.018200,
                  -0.000226,  0.018199,  0.999834] # Wanda

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
